# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job:
  displayName: 'Ubuntu develop'
  timeoutInMinutes: 0
  pool:
    vmImage: ubuntu-latest

  steps:  
  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b factory https://github.com/Nuitka/Nuitka.git Py2C'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b develop https://github.com/Nuitka/Nuitka.git Nuitka-develop'
      workingDirectory: '..'

  - task: Cache@2
    inputs:
      key: '"ubuntu-pipenv" | "$(Build.BuildNumber)"'
      path: '../pipenv_cache'
      restoreKeys: |
       "ubuntu-pipenv"

  - task: CmdLine@2
    inputs:
      script: 'python -m pip install -r requirements.txt'

  - task: CmdLine@2
    inputs:
      script: |
        export PIPENV_CACHE_DIR=$(pwd)/../pipenv_cache
        ../Nuitka-develop/bin/nuitka --version
        bash nuitka-release.sh

- job:
  displayName: 'MacOS develop'
  timeoutInMinutes: 0
  pool:
    vmImage: macos-latest

  steps:
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'macos_test_cert.p12'
      certPwd: 'test'
      keychain: 'temp'

  - task: CmdLine@2
    inputs:
      script: NONINTERACTIVE=1 sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b factory https://github.com/Nuitka/Nuitka.git Py2C'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b develop https://github.com/Nuitka/Nuitka.git Nuitka-develop'
      workingDirectory: '..'

  - task: Cache@2
    inputs:
      key: '"macos-pipenv" | "$(Build.BuildNumber)"'
      path: '../pipenv_cache'
      restoreKeys: |
       "macos-pipenv"

  - task: CmdLine@2
    inputs:
      script: 'python3.10 -m pip install -r requirements.txt'

  - task: CmdLine@2
    inputs:
      script: 'python3.11 -m pip install -r requirements.txt'

  - task: CmdLine@2
    inputs:
      script: |
        export PIPENV_CACHE_DIR=$(pwd)/../pipenv_cache
        python3.10 ../Nuitka-develop/bin/nuitka --version
        bash nuitka-release.sh

- job:
  displayName: 'Windows develop'
  timeoutInMinutes: 0
  pool:
    vmImage: windows-latest

  steps:
  - task: CmdLine@2
    inputs:
      script: |
        git clone --depth=1 -b factory https://github.com/Nuitka/Nuitka.git Py2C
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: |
        git clone --depth=1 -b develop https://github.com/Nuitka/Nuitka.git Nuitka-develop
      workingDirectory: '..'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - task: Cache@2
    inputs:
      key: '"windows-pipenv" | "$(Build.BuildNumber)"'
      path: '../pipenv_cache'
      restoreKeys: |
       "windows-pipenv"

  - task: CmdLine@2
    inputs:
      script: 'python.exe -m pip install -r requirements.txt'

  - task: CmdLine@2
    inputs:
      script: |
        @echo on
        set PIPENV_CACHE_DIR=%CD%\..\pipenv_cache
        if not exist "%PIPENV_CACHE_DIR%" mkdir %PIPENV_CACHE_DIR%
        python3 ..\Nuitka-develop\bin\nuitka --version
        python3 ../Py2C/bin/nuitka-watch --python-version=3.10 --no-pipenv-update --nuitka-binary=..\Nuitka-develop\bin\nuitka
