# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job:
  displayName: 'Ubuntu develop'
  timeoutInMinutes: 0
  pool:
    vmImage: ubuntu-latest

  steps:  
  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b factory https://github.com/Nuitka/Nuitka.git Py2C'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b develop https://github.com/Nuitka/Nuitka.git Nuitka-develop'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'python -m pip install -r requirements.txt'

  - task: Bash@3
    inputs:
      filePath: 'nuitka-release.sh'

- job:
  displayName: 'MacOS develop'
  timeoutInMinutes: 0
  pool:
    vmImage: macos-latest

  steps:
  - task: CmdLine@2
    inputs:
      script: 'curl -o python.pkg https://www.python.org/ftp/python/3.10.11/python-3.10.11-macos11.pkg'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'sudo installer -pkg python.pkg -target /'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b factory https://github.com/Nuitka/Nuitka.git Py2C'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b develop https://github.com/Nuitka/Nuitka.git Nuitka-develop'
      workingDirectory: '..'

  - task: Cache@2
    inputs:
      key: '"macos-pipenv" | "$(Build.BuildNumber)"'
      path: '~/Library/Caches/pipenv'
      restoreKeys: |
       "macos-pipenv"

  - task: CmdLine@2
    inputs:
      script: 'PATH=/usr/local/bin:$PATH python3 -m pip install -r requirements.txt'

  - task: Bash@3
    inputs:
      filePath: 'PATH=/usr/local/bin:$PATH nuitka-release.sh'

- job:
  displayName: 'Windows develop'
  timeoutInMinutes: 0
  pool:
    vmImage: windows-latest

  steps:
  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b factory https://github.com/Nuitka/Nuitka.git Py2C'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b develop https://github.com/Nuitka/Nuitka.git Nuitka-develop'
      workingDirectory: '..'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10.x'
      addToPath: true

  - task: CmdLine@2
    inputs:
      script: 'python.exe -m pip install -r requirements.txt'

  - task: CmdLine@2
    inputs:
      script: 'python3 ../Py2C/bin/nuitka-watch --python-version=3.10 --no-pipenv-update --nuitka-binary=../Nuitka-develop/bin/nuitka'