# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'git clone --shallow -b factory https://github.com/Nuitka/Nuitka.git Py2C'
    workingDirectory: '..'

- task: CmdLine@2
  inputs:
    script: 'git clone --shallow -b develop https://github.com/Nuitka/Nuitka.git Nuitka-develop'
    workingDirectory: '..'

- task: Bash@3
  inputs:
    filePath: 'nuitka-release.sh'