pr:
  branches:
    include:
    - '*'

jobs:
- job:
  displayName: 'Ubuntu develop'
  timeoutInMinutes: 0
  pool: DevOps-Ubuntu

  steps:  
  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b factory https://github.com/Nuitka/Nuitka.git Py2C'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b develop https://github.com/Nuitka/Nuitka.git Nuitka-develop'
      workingDirectory: '..'

  - task: Cache@2
    inputs:
      key: '"ubuntu-pipenv" | "$(Build.BuildNumber)"'
      path: '../pipenv_cache'
      restoreKeys: |
       "ubuntu-pipenv"

  - task: CmdLine@2
    inputs:
      script: 'python3.11 -m pip install -r requirements.txt'

  - task: CmdLine@2
    inputs:
      script: |
        export PIPENV_CACHE_DIR=$(pwd)/../pipenv_cache
        python3.11 ../Nuitka-develop/bin/nuitka --version
        python3.11 ../Py2C/bin/nuitka-watch --python-version=3.11 --no-pipenv-update --nuitka-binary=../Nuitka-develop/bin/nuitka

- job:
  displayName: 'MacOS develop'
  timeoutInMinutes: 0
  pool:
    vmImage: macos-latest

  steps:
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'macos_test_cert.p12'
      certPwd: 'test'
      keychain: 'temp'

  - task: CmdLine@2
    inputs:
      script: NONINTERACTIVE=1 sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

  - task: CmdLine@2
    inputs:
      script: 'curl -o python.pkg https://www.python.org/ftp/python/3.10.11/python-3.10.11-macos11.pkg'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'sudo installer -pkg python.pkg -target /'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'sudo bash "/Applications/Python 3.10/Install Certificates.command"'

  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b factory https://github.com/Nuitka/Nuitka.git Py2C'
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: 'git clone --depth=1 -b develop https://github.com/Nuitka/Nuitka.git Nuitka-develop'
      workingDirectory: '..'

  - task: Cache@2
    inputs:
      key: '"macos-pipenv" | "$(Build.BuildNumber)"'
      path: '../pipenv_cache'
      restoreKeys: |
       "macos-pipenv"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11' 

  - task: CmdLine@2
    inputs:
      script: 'python3.11 -m pip install -r requirements.txt'
    
  - task: CmdLine@2
    inputs:
      script: 'PATH=/Library/Frameworks/Python.framework/Versions/3.10/bin:$PATH python3.10 -m pip install -r requirements.txt'

  - task: CmdLine@2
    inputs:
      script: |
        export PIPENV_CACHE_DIR=$(pwd)/../pipenv_cache
        export PATH=/Library/Frameworks/Python.framework/Versions/3.10/bin:$PATH
        python3.10 ../Nuitka-develop/bin/nuitka --version
        bash nuitka-release.sh

- job:
  displayName: 'Windows develop'
  timeoutInMinutes: 0
  pool: DevOps-Windows

  steps:
  - task: CmdLine@2
    inputs:
      script: |
        git clone --depth=1 -b factory https://github.com/Nuitka/Nuitka.git Py2C
      workingDirectory: '..'

  - task: CmdLine@2
    inputs:
      script: |
        git clone --depth=1 -b develop https://github.com/Nuitka/Nuitka.git Nuitka-develop
      workingDirectory: '..'

  - task: Cache@2
    inputs:
      key: '"windows-pipenv" | "$(Build.BuildNumber)"'
      path: '../pipenv_cache'
      restoreKeys: |
       "windows-pipenv"

  - task: CmdLine@2
    inputs:
      script: 'python -m pip install -r requirements.txt'

  - task: CmdLine@2
    inputs:
      script: |
        @echo on
        set PIPENV_CACHE_DIR=%CD%\..\pipenv_cache
        if not exist "%PIPENV_CACHE_DIR%" mkdir %PIPENV_CACHE_DIR%
        python ..\Nuitka-develop\bin\nuitka --version
        python ../Py2C/bin/nuitka-watch --python-version=3.11 --no-pipenv-update --nuitka-binary=..\Nuitka-develop\bin\nuitka
